function f = ffunc(t,in2,in3)
%FFUNC
%    F = FFUNC(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    11-Nov-2023 11:40:03

dth1_ = in3(1,:);
dth2_ = in3(2,:);
th1_ = in2(1,:);
th2_ = in2(2,:);
t2 = cos(th1_);
t3 = sin(th1_);
t4 = dth1_+dth2_;
t5 = th1_+th2_;
t6 = dth1_.^2;
t7 = cos(t5);
t8 = sin(t5);
t9 = t4.^2;
t10 = t3.*t6;
t11 = t2.*t6;
t12 = t10./2.0;
t13 = t11./2.0;
t14 = t8.*(4.9e+1./1.0e+1);
t16 = (t7.*t9)./2.0;
t17 = (t7.*t9)./4.0;
t18 = (t8.*t9)./2.0;
t19 = (t8.*t9)./4.0;
t15 = -t14;
t20 = t10+t18;
t21 = t11+t16;
t22 = t12+t19;
t23 = t13+t17;
f = [t3.*(-1.47e+2./1.0e+1)+t15+t22.*(t2+t7./2.0)-t23.*(t3+t8./2.0)+t20.*(t2./2.0+t7./4.0)-t21.*(t3./2.0+t8./4.0);t15+(t7.*t20)./4.0+(t7.*t22)./2.0-(t8.*t21)./4.0-(t8.*t23)./2.0];
end
