function b = bfunc(T,Fmax)
%BFUNC
%    B = BFUNC(T,Fmax)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    07-Dec-2023 18:51:33

b = [Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax;Fmax];
end
